# Библиотека `pandas`: часть 1

*Алла Тамбовцева*

## Домашнее задание 

### Описание домашнего задания и формат сдачи

В домашнем задании необходимо решить предложенные задачи по программированию – вписать свой код в ячейки после условий задач вместо комментария `### YOUR CODE HERE ###` в файле *homework-pandas1.ipynb* и сохранить изменения, используя опцию *Save and Checkpoint* из вкладки меню *File* или кнопку *Save and Checkpoint* на панели инструментов. Итоговый файл в формате `.ipynb` (файл Jupyter Notebook) необходимо загрузить в личный кабинет обучающей онлайн платформы Skillbox (https://go.skillbox.ru/) и отправить на проверку.

### Задание 1

Загрузить массив `NumPy` из файла `"arr_pandas.npy"` (как в задании к предыдущему модулю) и преобразовать его в датафрейм. Массив содержит данные по результатам соревнований Scottish Hill Races в 2000 году (полное описание на английском языке можно посмотреть на [странице](https://vincentarelbundock.github.io/Rdatasets/doc/DAAG/races2000.html) с документацией по исходному файлу с данными).

**Подсказка (преобразование в датафрейм):**

In [2]:
dat = pd.DataFrame(arr)  # arr - массив NumPy из файла

In [1]:
import pandas as pd
import numpy as np
arr = np.load("arr_pandas.npy", allow_pickle=True)

In [3]:
dat.head(4)

                    0   1     2         3         4       5
0  Aonach Mor Gondola   2  2000  0.403611  0.518889  uphill
1   Broughton Brewery   2   650  0.254444  0.316667   other
2         El-Brim-Ick   3   750  0.485833  0.389167   other
3  The Devils Burdens  21  4100   2.39972   3.09333   relay

### Задание 2

Определить, сколько в датафрейме строк и столбцов. Привести код и указать ответ в виде текста или комментария к коду.

In [8]:
dat.shape

(77, 6)

**Ответ:** 
77 строк
6 столбц

### Задание 3

Присвоить столбцам следующие названия (указаны с пояснениями): 

* `id`: id участника
* `dist`: расстояние в милях (по карте)
* `climb`: высота, достигнутая на маршруте (в сумме за весь маршрут, в футах)
* `time`: время (в часах)
* `timef`: время для женщин (в часах)
* `type`: тип гонки (*hill*, *marathon*, *relay*, *uphill* or *other*)

In [5]:
dat.columns = ['id','dist', 'climb', 'time', 'timef', 'type']

### Задание 4

Вывести на экран значение высоты, достигнутой на маршруте участником *Norman's Law*.

In [6]:
dat.iloc[7, 2]

700

### Задание 5
Вывести на экран значения показателей `dist`, `climb` , `time` для первых 10 участников.

In [7]:
dat.loc[0:9, 'dist':'time']

  dist climb      time
0    2  2000  0.403611
1    2   650  0.254444
2    3   750  0.485833
3   21  4100   2.39972
4    6  2500  0.782222
5    7  1800  0.793333
6  1.5  1400  0.314444
7    5   700  0.464167
8    6   900  0.546111
9    5  1200  0.623333

### Задание 6

Вывести на экран сводную информацию по датафрейму, которая включает типы всех столбцов. Сколько столбцов типа `float` в датафрейме? Привести ответ на вопрос в виде текста или комментария к коду.

In [9]:
dat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 6 columns):
id       77 non-null object
dist     77 non-null object
climb    77 non-null object
time     77 non-null object
timef    75 non-null object
type     77 non-null object
dtypes: object(6)
memory usage: 3.7+ KB

**Ответ:** 
object(6)
float - нет

### Задание 7

Выбрать строки, которые соответствуют участникам эстафеты (*relay*).

In [10]:
dat[dat['type'] == 'relay']

                    id dist climb      time     timef   type
3   The Devils Burdens   21  4100   2.39972   3.09333  relay
16             Ben Rha  7.5   800  0.738056  0.997222  relay
74              Elrick  3.6   650  0.358056    0.4425  relay

### Задание 8

Выбрать строки, которые соответствуют участникам гонки в холмах (*hill*), которые в сумме достигли высоты более 1000 футов. Посчитать, сколько таких участников.

In [12]:
dat[(dat['type'] == 'hill') & (dat['climb'] > 1000)]

                       id  dist climb      time     timef  type
4           Tiso Carnethy     6  2500  0.782222  0.919167  hill
5                 Criffel     7  1800  0.793333   1.00333  hill
6              Chapelgill   1.5  1400  0.314444  0.376667  hill
9             Knockfarrel     5  1200  0.623333  0.734167  hill
10                 Screel     4  1300  0.458889  0.543611  hill
11      O.P.S. Clachnaben  10.5  3500   1.27889   1.48778  hill
17          Stuc A'Chroin    14  5000   1.98333   2.39889  hill
18            29th Dumyat     5  1250  0.552778  0.637778  hill
19             Ben Lomond     9  3192   1.03778   1.19917  hill
21               Goatfell     8  2866   1.22778   1.52639  hill
22  Scottish Nuclear Kaim   3.5  1250  0.431111      0.54  hill
28           12 Trig Trog    46  7500   8.30694   13.5478  hill
29            Kilpatricks     6  1400  0.739722  0.874167  hill
32                Yetholm     8  2500   1.19306   1.45111  hill
33             Ben Sheann   2.5  1400  0.381667  0.484722  hill
34              Glen Rosa    13  5500   2.22028   2.70472  hill
37       Scottish Borders    10  2000   1.19806   1.44972  hill
40                Cort-ma     6  1500  0.742222  0.870278  hill
42                 Dollar     6  2000  0.638333  0.773611  hill
43                Ben Tee     9  2950   1.32778   1.78278  hill
45                Glamaig   4.5  2400  0.744722  0.936111  hill
46              Urie Loch     6  1400  0.773889     1.015  hill
48       Meall Ant-Suidhe   3.5  1500     0.465  0.609722  hill
52              Mash Hill     6  2500  0.794167   1.05194  hill
53            Ben Rhinnes    14  4900   1.97611   2.35583  hill
55             Creag Dubh     3  1223  0.463889  0.601667  hill
56             Glen Clova    15  5500   2.56722   2.96222  hill
59            Tap O'North     6  1220  0.665833  0.817778  hill
60                Lomonds     9  2200   1.05306   1.29389  hill
62              Ben Nevis    10  4400   1.42611   1.72361  hill
64        Moffat Beef Tub     2  1500  0.332222  0.436944  hill
65          Cairn William     6  1400  0.704444  0.809722  hill
66          Corrieyairick    16  2250   1.66472   1.96333  hill
67                 Morven     5  1700  0.609167  0.785833  hill
68                Merrick     8  2710   1.13333   1.39472  hill
69          Two Breweries    18  4900   2.56583   3.08833  hill
70            Manor Water    10  2300   1.18444    1.4975  hill
71               Pentland    16  6200   2.37778     2.785  hill
72                  Tinto   4.5  1500  0.499444  0.581111  hill

In [13]:
nameh = dat[(dat['type'] == 'hill') & (dat['climb'] >= 1000)] 
nameh.count()

id       39
dist     39
climb    39
time     39
timef    39
type     39
dtype: int64

**Ответ:** 
    39

### Задание 9

Выбрать строки, соответствующие участникам, которые либо достигли высоты более 4000 футов, либо потратили менее 0.5 часов.

In [15]:
dat[(dat['climb'] > 4000) | (dat['time'] < 0.5)]

                       id  dist climb      time     timef      type
0      Aonach Mor Gondola     2  2000  0.403611  0.518889    uphill
1       Broughton Brewery     2   650  0.254444  0.316667     other
2             El-Brim-Ick     3   750  0.485833  0.389167     other
3      The Devils Burdens    21  4100   2.39972   3.09333     relay
6              Chapelgill   1.5  1400  0.314444  0.376667      hill
7            Norman's Law     5   700  0.464167  0.609167      hill
10                 Screel     4  1300  0.458889  0.543611      hill
12            Hunters Bog   4.5   800  0.409444  0.477778     other
13         Aberfoyle Dash     3  1000    0.3375  0.381389    uphill
14          Manx Mountain  30.5  8000   4.46972   5.52333  marathon
15          Whangie Whizz   3.5   800  0.395556  0.464167      hill
17          Stuc A'Chroin    14  5000   1.98333   2.39889      hill
20               Kinnoull     4   800  0.387222    0.4525      hill
22  Scottish Nuclear Kaim   3.5  1250  0.431111      0.54      hill
25           Isle of Jura    16  7500   3.11639   3.83944     other
26                 Scolty     5   800  0.495833  0.579167      hill
28           12 Trig Trog    46  7500   8.30694   13.5478      hill
33             Ben Sheann   2.5  1400  0.381667  0.484722      hill
34              Glen Rosa    13  5500   2.22028   2.70472      hill
35      West Highland Way    95  9200   15.4389   18.8792     other
38             Eildon Two   4.5  1500  0.427222  0.507778     other
44             Black Hill     4   600  0.447778  0.532222      hill
48       Meall Ant-Suidhe   3.5  1500     0.465  0.609722      hill
50            Lochaber AC     2   900  0.284722  0.360556      hill
51      Lochaber Highland     2   900  0.294167  0.473056      hill
53            Ben Rhinnes    14  4900   1.97611   2.35583      hill
55             Creag Dubh     3  1223  0.463889  0.601667      hill
56             Glen Clova    15  5500   2.56722   2.96222      hill
57             Caerketton   2.5   800  0.208611  0.246667      hill
61                   Oban  2.25   500  0.232222  0.298889      hill
62              Ben Nevis    10  4400   1.42611   1.72361      hill
63                Braemar     4  2000  0.407778       NaN     other
64        Moffat Beef Tub     2  1500  0.332222  0.436944      hill
69          Two Breweries    18  4900   2.56583   3.08833      hill
71               Pentland    16  6200   2.37778     2.785      hill
72                  Tinto   4.5  1500  0.499444  0.581111      hill
74                 Elrick   3.6   650  0.358056    0.4425     relay
75                Gondola   2.5  2000  0.387222  0.518889    uphill
76            Greenmantle     2   650  0.254444  0.316667     other

### Задание 10

Создать столбец `time_min`, который содержит время маршрута, измеренное в минутах.

In [16]:
dat['time_min'] = dat['time'] * 60
dat

                       id  dist climb      time     timef      type time_min
0      Aonach Mor Gondola     2  2000  0.403611  0.518889    uphill  24.2167
1       Broughton Brewery     2   650  0.254444  0.316667     other  15.2667
2             El-Brim-Ick     3   750  0.485833  0.389167     other    29.15
3      The Devils Burdens    21  4100   2.39972   3.09333     relay  143.983
4           Tiso Carnethy     6  2500  0.782222  0.919167      hill  46.9333
5                 Criffel     7  1800  0.793333   1.00333      hill     47.6
6              Chapelgill   1.5  1400  0.314444  0.376667      hill  18.8667
7            Norman's Law     5   700  0.464167  0.609167      hill    27.85
8            Craig Dunain     6   900  0.546111  0.625833      hill  32.7667
9             Knockfarrel     5  1200  0.623333  0.734167      hill     37.4
10                 Screel     4  1300  0.458889  0.543611      hill  27.5333
11      O.P.S. Clachnaben  10.5  3500   1.27889   1.48778      hill  76.7333
12            Hunters Bog   4.5   800  0.409444  0.477778     other  24.5667
13         Aberfoyle Dash     3  1000    0.3375  0.381389    uphill    20.25
14          Manx Mountain  30.5  8000   4.46972   5.52333  marathon  268.183
15          Whangie Whizz   3.5   800  0.395556  0.464167      hill  23.7333
16                Ben Rha   7.5   800  0.738056  0.997222     relay  44.2833
17          Stuc A'Chroin    14  5000   1.98333   2.39889      hill      119
18            29th Dumyat     5  1250  0.552778  0.637778      hill  33.1667
19             Ben Lomond     9  3192   1.03778   1.19917      hill  62.2667
20               Kinnoull     4   800  0.387222    0.4525      hill  23.2333
21               Goatfell     8  2866   1.22778   1.52639      hill  73.6667
22  Scottish Nuclear Kaim   3.5  1250  0.431111      0.54      hill  25.8667
23             Ardoch Rig     7   600  0.678889  0.837222      hill  40.7333
24            Culter Fell    12  4000   1.72167   1.98778     other    103.3
25           Isle of Jura    16  7500   3.11639   3.83944     other  186.983
26                 Scolty     5   800  0.495833  0.579167      hill    29.75
27              Cornalees   5.5   800  0.618333       NaN      hill     37.1
28           12 Trig Trog    46  7500   8.30694   13.5478      hill  498.417
29            Kilpatricks     6  1400  0.739722  0.874167      hill  44.3833
..                    ...   ...   ...       ...       ...       ...      ...
47               Whiteash   5.5   728  0.508889  0.768333      hill  30.5333
48       Meall Ant-Suidhe   3.5  1500     0.465  0.609722      hill     27.9
49         Half Ben Nevis     5  1200  0.794167   1.03083     other    47.65
50            Lochaber AC     2   900  0.284722  0.360556      hill  17.0833
51      Lochaber Highland     2   900  0.294167  0.473056      hill    17.65
52              Mash Hill     6  2500  0.794167   1.05194      hill    47.65
53            Ben Rhinnes    14  4900   1.97611   2.35583      hill  118.567
54              Beinn Lee     7   500  0.716667  0.943333      hill       43
55             Creag Dubh     3  1223  0.463889  0.601667      hill  27.8333
56             Glen Clova    15  5500   2.56722   2.96222      hill  154.033
57             Caerketton   2.5   800  0.208611  0.246667      hill  12.5167
58               Wideford   5.5   741  0.563611  0.724167      hill  33.8167
59            Tap O'North     6  1220  0.665833  0.817778      hill    39.95
60                Lomonds     9  2200   1.05306   1.29389      hill  63.1833
61                   Oban  2.25   500  0.232222  0.298889      hill  13.9333
62              Ben Nevis    10  4400   1.42611   1.72361      hill  85.5667
63                Braemar     4  2000  0.407778       NaN     other  24.4667
64        Moffat Beef Tub     2  1500  0.332222  0.436944      hill  19.9333
65          Cairn William     6  1400  0.704444  0.809722      hill  42.2667
66          Corrieyairick    16  2250   1.66472   1.96333      hill  99.8833
67                 Morven     5  1700  0.609167  0.785833      hill    36.55
68                Merrick     8  2710   1.13333   1.39472      hill       68
69          Two Breweries    18  4900   2.56583   3.08833      hill   153.95
70            Manor Water    10  2300   1.18444    1.4975      hill  71.0667
71               Pentland    16  6200   2.37778     2.785      hill  142.667
72                  Tinto   4.5  1500  0.499444  0.581111      hill  29.9667
73             Druim Fada   6.5  1000  0.751111  0.972222     other  45.0667
74                 Elrick   3.6   650  0.358056    0.4425     relay  21.4833
75                Gondola   2.5  2000  0.387222  0.518889    uphill  23.2333
76            Greenmantle     2   650  0.254444  0.316667     other  15.2667

[77 rows x 7 columns]

### Задание 11

Создать столбец `year` с годом соревнований (везде 2000 год). Внимание: столбец с годом должен быть числовым (целочисленным).

In [17]:
dat['year'] = 2000
dat

,id,dist,climb,time,timef,type,time_min,year
0,Aonach Mor Gondola,2,2000,0.403611,0.518889,uphill,24.2167,2000
1,Broughton Brewery,2,650,0.254444,0.316667,other,15.2667,2000
2,El-Brim-Ick,3,750,0.485833,0.389167,other,29.15,2000
3,The Devils Burdens,21,4100,2.39972,3.09333,relay,143.983,2000
4,Tiso Carnethy,6,2500,0.782222,0.919167,hill,46.9333,2000
5,Criffel,7,1800,0.793333,1.00333,hill,47.6,2000
6,Chapelgill,1.5,1400,0.314444,0.376667,hill,18.8667,2000
7,Norman's Law,5,700,0.464167,0.609167,hill,27.85,2000
8,Craig Dunain,6,900,0.546111,0.625833,hill,32.7667,2000
9,Knockfarrel,5,1200,0.623333,0.734167,hill,37.4,2000
10,Screel,4,1300,0.458889,0.543611,hill,27.5333,2000
11,O.P.S. Clachnaben,10.5,3500,1.27889,1.48778,hill,76.7333,2000
12,Hunters Bog,4.5,800,0.409444,0.477778,other,24.5667,2000
13,Aberfoyle Dash,3,1000,0.3375,0.381389,uphill,20.25,2000
14,Manx Mountain,30.5,8000,4.46972,5.52333,marathon,268.183,2000
15,Whangie Whizz,3.5,800,0.395556,0.464167,hill,23.7333,2000
16,Ben Rha,7.5,800,0.738056,0.997222,relay,44.2833,2000
17,Stuc A'Chroin,14,5000,1.98333,2.39889,hill,119,2000
18,29th Dumyat,5,1250,0.552778,0.637778,hill,33.1667,2000
19,Ben Lomond,9,3192,1.03778,1.19917,hill,62.2667,2000
20,Kinnoull,4,800,0.387222,0.4525,hill,23.2333,2000
21,Goatfell,8,2866,1.22778,1.52639,hill,73.6667,2000
22,Scottish Nuclear Kaim,3.5,1250,0.431111,0.54,hill,25.8667,2000
23,Ardoch Rig,7,600,0.678889,0.837222,hill,40.7333,2000
24,Culter Fell,12,4000,1.72167,1.98778,other,103.3,2000
25,Isle of Jura,16,7500,3.11639,3.83944,other,186.983,2000
26,Scolty,5,800,0.495833,0.579167,hill,29.75,2000
27,Cornalees,5.5,800,0.618333,NaN,hill,37.1,2000
28,12 Trig Trog,46,7500,8.30694,13.5478,hill,498.417,2000
29,Kilpatricks,6,1400,0.739722,0.874167,hill,44.3833,2000
...,...,...,...,...,...,...,...,...
47,Whiteash,5.5,728,0.508889,0.768333,hill,30.5333,2000
48,Meall Ant-Suidhe,3.5,1500,0.465,0.609722,hill,27.9,2000
49,Half Ben Nevis,5,1200,0.794167,1.03083,other,47.65,2000
50,Lochaber AC,2,900,0.284722,0.360556,hill,17.0833,2000
51,Lochaber Highland,2,900,0.294167,0.473056,hill,17.65,2000
52,Mash Hill,6,2500,0.794167,1.05194,hill,47.65,2000
53,Ben Rhinnes,14,4900,1.97611,2.35583,hill,118.567,2000
54,Beinn Lee,7,500,0.716667,0.943333,hill,43,2000
55,Creag Dubh,3,1223,0.463889,0.601667,hill,27.8333,2000
56,Glen Clova,15,5500,2.56722,2.96222,hill,154.033,2000
57,Caerketton,2.5,800,0.208611,0.246667,hill,12.5167,2000
58,Wideford,5.5,741,0.563611,0.724167,hill,33.8167,2000
59,Tap O'North,6,1220,0.665833,0.817778,hill,39.95,2000
60,Lomonds,9,2200,1.05306,1.29389,hill,63.1833,2000
61,Oban,2.25,500,0.232222,0.298889,hill,13.9333,2000
62,Ben Nevis,10,4400,1.42611,1.72361,hill,85.5667,2000
63,Braemar,4,2000,0.407778,NaN,other,24.4667,2000
64,Moffat Beef Tub,2,1500,0.332222,0.436944,hill,19.9333,2000
65,Cairn William,6,1400,0.704444,0.809722,hill,42.2667,2000
66,Corrieyairick,16,2250,1.66472,1.96333,hill,99.8833,2000
67,Morven,5,1700,0.609167,0.785833,hill,36.55,2000
68,Merrick,8,2710,1.13333,1.39472,hill,68,2000
69,Two Breweries,18,4900,2.56583,3.08833,hill,153.95,2000
70,Manor Water,10,2300,1.18444,1.4975,hill,71.0667,2000
71,Pentland,16,6200,2.37778,2.785,hill,142.667,2000
72,Tinto,4.5,1500,0.499444,0.581111,hill,29.9667,2000
73,Druim Fada,6.5,1000,0.751111,0.972222,other,45.0667,2000
74,Elrick,3.6,650,0.358056,0.4425,relay,21.4833,2000
75,Gondola,2.5,2000,0.387222,0.518889,uphill,23.2333,2000
76,Greenmantle,2,650,0.254444,0.316667,other,15.2667,2000

.<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> 
# Дополнительное (необязательное) задание.
<br>

### Задание 1

Загрузить датафрейм из файла `extraversion.csv`, используя код ниже. При этом файл `extraversion.csv` должен находиться в той же папке, что и ноутбук с решениями. Его можно поместить в ту же папку, нажав кнопку *Upload* в *Home*.

In [ ]:
# кодировка UTF-8, чтобы кириллица корректно считывалась на Windows
ps = pd.read_csv("extraversion.csv", encoding = "UTF-8")

Файл содержит результаты учебного психометрического исследования, целью которого является выявление связи между уровнем экстраверсии человека и его склонности к участию в волонтёрской деятельности. Датафрейм содержит следующие столбцы:

* `sex`: пол респондента (Женский, Мужской);
* `volunteer`: регулярное участие в волонтёрской деятельности (Да, Нет);
* `Q 1` - `Q 57`: ответы на вопросы по анкете Айзенка (Да, Нет), информацию об анкете и сами вопросы можно найти на [этой](http://ipp.hse.ru/57-testytest-ajzenka-ekstraversiya-introversiya-nejrotizm) странице.

In [ ]:
### YOUR CODE HERE ###

### Задание 2

Определить, сколько в датафрейме строк и столбцов. Привести код и указать ответ в виде текста или комментария к коду.

In [ ]:
### YOUR CODE HERE ###

### Задание 3

Переименовать столбцы `Q 1`-`Q 57` в `Q1`-`Q57`, другими словами, убрать в названиях всех столбцов пробелы в середине (если есть). 

**Подсказка 1:** Метод `.replace()` для строк на [pythontutor.ru](https://pythontutor.ru/lessons/str/).

**Подсказка 2:** Для выполнения этого задания можно написать функцию, которая будет заменять пробелы на «пустоту», а потом применить её с помощью функции `map()` ко всем элементам списка. Пример ниже иллюстрирует применение функции для изменения регистра текста.

In [2]:
# Пример

L = ['яблоко', 'груша', 'слива']  # исходный список

# функция принимает на вход строку x и возвращает её же, 
# но большими буквами – метод .upper()

def f(x):
    """
    Input: x is a string.
    Output: x is a string.
    Makes all letters uppercase. 
    """
    return x.upper()

# результат: применяем функцию f к списку L через map и преобразуем в список
# можно убрать list() вначале и убедиться, что он здесь нужен

list(map(f, L))

['ЯБЛОКО', 'ГРУША', 'СЛИВА']

In [ ]:
### YOUR CODE HERE ###

### Задание 4

Выбрать столбцы `Q1`, `Q3`, `Q8`, `Q10`, `Q13`, `Q17`, `Q22`, `Q25`, `Q27`, `Q39`, `Q44`, `Q46`, `Q49`, `Q53`, `Q56` и сохранить их в отдельный датафрейм `extra_yes`. 

Выбрать столбцы `Q5`, `Q15`, `Q20`, `Q29`, `Q32`, `Q34`, `Q37`,`Q41`, `Q51` и сохранить их в отдельный датафрейм `extra_no`.

Эти столбцы будут использоваться для вычисления индекса экстраверсии.

In [ ]:
### YOUR CODE HERE ###

### Задание 5

Посчитать для каждой строки в датафрейме `extra_yes` число ответов `"Да"` и полученный результат сохранить в переменную `extra_yes_sum`. Посчитать для каждой строки в датафрейме `extra_no` число ответов `"Нет"` и полученный результат сохранить в переменную `extra_no_sum`.

**Подсказка 1:** метод `.isin()` для [датафреймов](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isin.html) `pandas`.

**Подсказка 2:** метод `.sum()` для [датафреймов](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sum.html) `pandas`.

In [ ]:
### YOUR CODE HERE ###

### Задание 6

Добавить в исходный датафрейм столбец `extra`, который представляет собой индекс экстраверсии, который считается так: сумма числа ответов "Да" в `extra_yes` и числа ответов "Нет" в `extra_no`.

In [ ]:
### YOUR CODE HERE ###

### Задание 7

Добавить в исходный датафрейм столбец `female`, состоящий из значений 0 и 1 (0 — Мужской, 1 — Женский). 

**Подсказка:** возможно, пригодится метод `.astype()` для [Series](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.Series.astype.html) в `pandas`, он преобразует типы столбцов.

In [ ]:
### YOUR CODE HERE ###

### Задание 8

Выбрать из исходного датафрейма строки, которые соответствуют либо волонтёрам с индексом экстраверсии выше 15, либо не-волонтёрам с индексом экстраверсии ниже 15. Сохранить в датафрейм `pure`.

In [ ]:
### YOUR CODE HERE ###

### Задание 9

Определить (любым способом, кроме явного подсчёта), сколько волонтёров и не-волонтёров в датафрейме `pure`.

In [ ]:
### YOUR CODE HERE ###

### Задание 10

Определить минимальное, максимальное, среднее и медианное значение индекса экстраверсии в датафрейме `pure`. Сохранить полученные результаты в отдельные переменные (их должно быть 4).

Добавить в датафрейм `pure` столбец `high`, состоящий из 0 и 1, где 1 соответствует респондентам, уровень экстраверсии которых выше значения $m = \max\{\text{median}, \text{mean}\}$, то есть максимума из медианного и среднего значения, а 0 — респондентам с уровнем экстраверсии не выше $m$.

In [ ]:
### YOUR CODE HERE ###